"use strict";

/**
 * Curated universe of NSE stocks per sector for the Stock Momentum Radar.
 * Each entry is { symbol, label } where symbol is the Yahoo Finance ticker (with .NS suffix).
 *
 * Find Yahoo Finance tickers at: https://finance.yahoo.com  (search NSE symbol → append .NS)
 */
module.exports.STOCK_SECTORS = {
  "IT": [
    { symbol: "TCS.NS",         label: "TCS" },
    { symbol: "INFY.NS",        label: "Infosys" },
    { symbol: "HCLTECH.NS",     label: "HCL Tech" },
    { symbol: "WIPRO.NS",       label: "Wipro" },
    { symbol: "TECHM.NS",       label: "Tech Mahindra" },
    { symbol: "COFORGE.NS",     label: "Coforge" },
    { symbol: "PERSISTENT.NS",  label: "Persistent Systems" },
    { symbol: "MPHASIS.NS",     label: "Mphasis" },
    { symbol: "OFSS.NS",        label: "Oracle Fin Services" },
    { symbol: "NETWEB.NS",      label: "Netweb Technologies" },
    { symbol: "TECHNOE.NS",     label: "Techno Electric" },
  ],
  "Banking - Private": [
    { symbol: "HDFCBANK.NS",    label: "HDFC Bank" },
    { symbol: "ICICIBANK.NS",   label: "ICICI Bank" },
    { symbol: "KOTAKBANK.NS",   label: "Kotak Bank" },
    { symbol: "AXISBANK.NS",    label: "Axis Bank" },
    { symbol: "INDUSINDBK.NS",  label: "IndusInd Bank" },
    { symbol: "FEDERALBNK.NS",  label: "Federal Bank" },
    { symbol: "IDFCFIRSTB.NS",  label: "IDFC First Bank" },
    { symbol: "RBLBANK.NS",     label: "RBL Bank" },
  ],
  "Banking - PSU": [
    { symbol: "SBIN.NS",        label: "SBI" },
    { symbol: "BANKBARODA.NS",  label: "Bank of Baroda" },
    { symbol: "PNB.NS",         label: "PNB" },
    { symbol: "CANBK.NS",       label: "Canara Bank" },
    { symbol: "UNIONBANK.NS",   label: "Union Bank" },
    { symbol: "INDIANB.NS",     label: "Indian Bank" },
  ],
  "Auto & EV": [
    { symbol: "MARUTI.NS",      label: "Maruti" },
    { symbol: "M&M.NS",         label: "M&M" },
    { symbol: "ASHOKLEY.NS",    label: "Ashok Leyland" },
    { symbol: "BAJAJ-AUTO.NS",  label: "Bajaj Auto" },
    { symbol: "HEROMOTOCO.NS",  label: "Hero MotoCorp" },
    { symbol: "EICHERMOT.NS",   label: "Eicher Motors" },
    { symbol: "TIINDIA.NS",     label: "Tube Investments" },
    { symbol: "MOTHERSON.NS",   label: "Samvardhana Motherson" },
    { symbol: "ENDURANCE.NS",   label: "Endurance Technologies" },
    { symbol: "OLAELEC.NS",     label: "Ola Electric" },
    { symbol: "SONACOMS.NS",    label: "Sona BLW Precision" },
    { symbol: "MINDACORP.NS",   label: "Minda Corp" },
  ],
  "Pharma": [
    { symbol: "SUNPHARMA.NS",   label: "Sun Pharma" },
    { symbol: "DRREDDY.NS",     label: "Dr. Reddy's" },
    { symbol: "CIPLA.NS",       label: "Cipla" },
    { symbol: "DIVISLAB.NS",    label: "Divis Labs" },
    { symbol: "APOLLOHOSP.NS",  label: "Apollo Hospitals" },
    { symbol: "AUROPHARMA.NS",  label: "Aurobindo Pharma" },
    { symbol: "LUPIN.NS",       label: "Lupin" },
    { symbol: "BIOCON.NS",      label: "Biocon" },
    { symbol: "TORNTPHARM.NS",  label: "Torrent Pharma" },
    { symbol: "JBCHEPHARM.NS",  label: "JB Chemicals" },
    { symbol: "GRANULES.NS",    label: "Granules India" },
    { symbol: "WOCKPHARMA.NS",  label: "Wockhardt" },
    { symbol: "ZYDUSLIFE.NS",   label: "Zydus Lifesciences" },
    { symbol: "NAVINFLUOR.NS",  label: "Navin Fluorine" },
    { symbol: "NH.NS",          label: "Narayana Hrudayalaya" },
  ],
  "FMCG": [
    { symbol: "HINDUNILVR.NS",  label: "HUL" },
    { symbol: "ITC.NS",         label: "ITC" },
    { symbol: "NESTLEIND.NS",   label: "Nestle" },
    { symbol: "BRITANNIA.NS",   label: "Britannia" },
    { symbol: "DABUR.NS",       label: "Dabur" },
    { symbol: "MARICO.NS",      label: "Marico" },
    { symbol: "GODREJCP.NS",    label: "Godrej Consumer" },
    { symbol: "VBL.NS",         label: "Varun Beverages" },
    { symbol: "HONASA.NS",      label: "Honasa Consumer" },
  ],
  "Metals & Mining": [
    { symbol: "TATASTEEL.NS",   label: "Tata Steel" },
    { symbol: "JSWSTEEL.NS",    label: "JSW Steel" },
    { symbol: "HINDALCO.NS",    label: "Hindalco" },
    { symbol: "VEDL.NS",        label: "Vedanta" },
    { symbol: "COALINDIA.NS",   label: "Coal India" },
    { symbol: "SAIL.NS",        label: "SAIL" },
    { symbol: "NATIONALUM.NS",  label: "NALCO" },
    { symbol: "WELCORP.NS",     label: "Welspun Corp" },
    { symbol: "SHYAMMETL.NS",   label: "Shyam Metalics" },
  ],
  "Energy & Oil": [
    { symbol: "RELIANCE.NS",    label: "Reliance" },
    { symbol: "ONGC.NS",        label: "ONGC" },
    { symbol: "IOC.NS",         label: "IOC" },
    { symbol: "BPCL.NS",        label: "BPCL" },
    { symbol: "NTPC.NS",        label: "NTPC" },
    { symbol: "POWERGRID.NS",   label: "Power Grid" },
    { symbol: "TATAPOWER.NS",   label: "Tata Power" },
    { symbol: "GAIL.NS",        label: "GAIL" },
    { symbol: "ATGL.NS",        label: "Adani Total Gas" },
    { symbol: "ADANIPOWER.NS",  label: "Adani Power" },
    { symbol: "ADANIGREEN.NS",  label: "Adani Green" },
    { symbol: "ADANIENSOL.NS",  label: "Adani Energy Solutions" },
    { symbol: "JSWENERGY.NS",   label: "JSW Energy" },
    { symbol: "JPPOWER.NS",     label: "Jaiprakash Power" },
    { symbol: "POWERINDIA.NS",  label: "Hitachi Energy India" },
    { symbol: "TRITURBINE.NS",  label: "Triveni Turbine" },
    { symbol: "PREMIERENE.NS",  label: "Premier Energies" },
    { symbol: "EMMVEE.NS",      label: "Emmvee Solar" },
    { symbol: "ATHERENERG.NS",  label: "Ather Energy" },
  ],
  "Capital Goods & Defence": [
    { symbol: "LT.NS",          label: "L&T" },
    { symbol: "ABB.NS",         label: "ABB India" },
    { symbol: "SIEMENS.NS",     label: "Siemens" },
    { symbol: "HAL.NS",         label: "HAL" },
    { symbol: "BEL.NS",         label: "BEL" },
    { symbol: "BHEL.NS",        label: "BHEL" },
    { symbol: "COCHINSHIP.NS",  label: "Cochin Shipyard" },
    { symbol: "CGPOWER.NS",     label: "CG Power" },
    { symbol: "HONAUT.NS",      label: "Honeywell Automation" },
    { symbol: "TIMKEN.NS",      label: "Timken India" },
    { symbol: "THERMAX.NS",     label: "Thermax" },
    { symbol: "CUMMINSIND.NS",  label: "Cummins India" },
    { symbol: "KIRLOSENG.NS",   label: "Kirloskar Electric" },
    { symbol: "HBLENGINE.NS",   label: "HBL Engineering" },
    { symbol: "3MINDIA.NS",     label: "3M India" },
    { symbol: "GMRAIRPORT.NS",  label: "GMR Airports" },
    { symbol: "GVT&D.NS",       label: "GVT&D" },
    { symbol: "SCHNEIDER.NS",   label: "Schneider Electric" },
  ],
  "Finance - NBFC": [
    { symbol: "BAJFINANCE.NS",  label: "Bajaj Finance" },
    { symbol: "BAJAJFINSV.NS",  label: "Bajaj Finserv" },
    { symbol: "CHOLAFIN.NS",    label: "Cholamandalam" },
    { symbol: "MUTHOOTFIN.NS",  label: "Muthoot Finance" },
    { symbol: "LICHSGFIN.NS",   label: "LIC Housing" },
    { symbol: "M&MFIN.NS",      label: "M&M Finance" },
    { symbol: "MANAPPURAM.NS",  label: "Manappuram Finance" },
    { symbol: "ANGELONE.NS",    label: "Angel One" },
    { symbol: "BSE.NS",         label: "BSE" },
    { symbol: "ICICIAMC.NS",    label: "ICICI Pru AMC" },
    { symbol: "SAMMAANCAP.NS",  label: "Sammaan Capital" },
    { symbol: "SAILIFE.NS",     label: "SBI Life" },
  ],
  "Real Estate": [
    { symbol: "DLF.NS",         label: "DLF" },
    { symbol: "GODREJPROP.NS",  label: "Godrej Properties" },
    { symbol: "OBEROIRLTY.NS",  label: "Oberoi Realty" },
    { symbol: "PRESTIGE.NS",    label: "Prestige Estates" },
    { symbol: "PHOENIXLTD.NS",  label: "Phoenix Mills" },
    { symbol: "SOBHA.NS",       label: "Sobha" },
  ],
  "Telecom": [
    { symbol: "BHARTIARTL.NS",  label: "Airtel" },
    { symbol: "INDUSTOWER.NS",  label: "Indus Towers" },
    { symbol: "IDEA.NS",        label: "Vodafone Idea" },
    { symbol: "TATACOMM.NS",    label: "Tata Communications" },
    { symbol: "HFCL.NS",        label: "HFCL" },
  ],
  "Consumption & Retail": [
    { symbol: "DMART.NS",       label: "DMart" },
    { symbol: "TRENT.NS",       label: "Trent" },
    { symbol: "TITAN.NS",       label: "Titan" },
    { symbol: "PAGEIND.NS",     label: "Page Industries" },
    { symbol: "BATAINDIA.NS",   label: "Bata India" },
    { symbol: "NYKAA.NS",       label: "Nykaa" },
    { symbol: "DIXON.NS",       label: "Dixon Technologies" },
    { symbol: "CPPLUS.NS",      label: "CP Plus" },
    { symbol: "USHAMART.NS",    label: "Usha Martin" },
    { symbol: "BLUEJET.NS",     label: "Blue Jet Healthcare" },
    { symbol: "APARINDS.NS",    label: "Apar Industries" },
  ],
  "Chemicals & Fertilisers": [
    { symbol: "DEEPAKFERT.NS",  label: "Deepak Fertilisers" },
    { symbol: "CHAMBLFERT.NS",  label: "Chambal Fertilisers" },
    { symbol: "GRASIM.NS",      label: "Grasim Industries" },
    { symbol: "AIAENG.NS",      label: "AIA Engineering" },
    { symbol: "EXIDEIND.NS",    label: "Exide Industries" },
  ],
  "Cables & Electronics": [
    { symbol: "POLYCAB.NS",     label: "Polycab" },
    { symbol: "KEI.NS",         label: "KEI Industries" },
    { symbol: "RRKABEL.NS",     label: "RR Kabel" },
    { symbol: "FINCABLES.NS",   label: "Finolex Cables" },
    { symbol: "LLOYDSME.NS",    label: "Lloyds ME" },
    { symbol: "ADANIENT.NS",    label: "Adani Enterprises" },
  ],
  "Cement & Construction": [
    { symbol: "JSWCEMENT.NS",   label: "JSW Cement" },
    { symbol: "JSWDULUX.NS",    label: "JSW Paints" },
    { symbol: "ACUTAAS.NS",     label: "Acutas" },
    { symbol: "CEMPRO.NS",      label: "Cement Products" },
  ],
  "Diversified": [
    { symbol: "IGIL.NS",        label: "India Grid InvIT" },
    { symbol: "ENRIN.NS",       label: "Enrin" },
  ],
};
